server:
  port: 8082

spring:
  application:
    name: springboot-webmagic
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.110.100:3306/manhua-webmagic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xiahan

## rabbitmq
  rabbitmq:
    host: 192.168.110.100
    username: admin
    password: admin
    virtual-host: /
    port: 5672
    # 开启confirms回调 P -> Exchange
    publisher-confirms: true
    # 开启returnedMessage回调 Exchange -> Queue
    publisher-returns: true
    # 设置手动确认(ack) Queue -> C
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100


## mybatis
mybatis:
#  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.xiahan.webmagic.entity
  configuration:
    map-underscore-to-camel-case: true

## webmagic
webmagic:
  url: zxa
  redishost: 192.168.110.100
  savePath: E:\\Temp\\1010\\
  cookie: as
  saveThread: 10

## TaskThreadPoolConfig
task:
  pool:
    corePoolSize: 10
    maxPoolSize: 11
    keepAliveSeconds: 30
    queueCapacity: 5000
    threadName: My-Executor-





## 日志
#logging:
#  level:
#    com.xiahan.webmagic.mapper: debug
